config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'
  get 'friendships/index'

  devise_for :users
  resources :posts, only: [:index, :create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :friendships
  resources :likes
  get '/likes/toggle_like' => "likes#toggle_like" , :as => :toggle
  root "posts#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  has_many :likes, as: :likeable
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :user, presence: true

	belongs_to :user
	has_many :comments, dependent: :destroy

	has_many :likes, as: :likeable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes


  has_many :friendships
  has_many :friends, through: :friendships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy]
  before_action :authorize_user, only: [:destroy]


  def create

  	@comment = Comment.new(comment_params)
  	@comment.user = current_user

  	@comment.save


    @post=@comment.post
    @com=@comment


  end


  	

  

  def destroy
  	@post = @comment.post

  	@comment.destroy
  	
  end

  private

  def comment_params
  	params.require(:comment).permit(:post_id, :content)
  end

  def set_comment
  	@comment = Comment.find(params[:id])
  end

  def authorize_user
  	if @comment.user != current_user
  		return redirect_to root_path
  	end
  	return true

  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController




def new

@friend = Friendship.new()
@myid=params[:id]

@friend.user_id = current_user.id


@friend.friend_id = params[:id]
@friend.save






end

def index
if user_signed_in?
	@user=User.all





end



end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController




def new
# container-variables
@class=params[:li]
@id=params[:id]


if @class=="Post"
# check if user has already liked that post exists
@here=Post.find(params[:id])
if Post.find(params[:id]).likes.find_by_user_id(current_user.id) == nil



# creating a new like of user for given post
@like=Like.new();
@like.user_id=current_user.id
@like.likeable_type=params[:li]
@like.likeable_id=params[:id]
@like.save
@liked="Unlike"

#if user has already liked a post
else
 @here.likes.find_by_user_id(current_user.id).destroy
 @liked="Like"

end

else

@here=Comment.find(params[:id])
if Comment.find(params[:id]).likes.find_by_user_id(current_user.id) == nil



# creating a new like of user for given post
@like=Like.new();
@like.user_id=current_user.id
@like.likeable_type=params[:li]
@like.likeable_id=params[:id]
@like.save
@liked="Unlike"

#if user has already liked a post
else
 @here.likes.find_by_user_id(current_user.id).destroy
 @liked="Like"
end
end


# else
# if params[:li]=="Comment"
# @here=Comment.find(params[:id])
# @here.likes.find_by_user_id(current_user).destroy
# end

# if params[:li]=="Post"
# @here=Post.find(params[:id])

# #@here.likes.find_by_user_id(current_user).destroy
# end

# @liked="unlike"
# @here2=Post.find(params[:p])

# @class=params[:li]
# @id=params[:id]






# end













end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_post, only: [:destroy]
  before_action :authorize_user, only: [:destroy]

  def index
  if user_signed_in?
    @user=current_user
    @friends=@user.friends
  end
  	@post = Post.new
  	@comment = Comment.new
  	@posts = Post.all.reverse()
  end

  def create
  	@post = Post.new(post_params)
  	@post.user = current_user
  	@post.save
  	@comment = Comment.new

  end

  def destroy
    @post_id = @post.id
  	@post.destroy
  	
  end

  private

  def post_params
  	params.require(:post).permit(:content)
  end

  def set_post
  	@post = Post.find(params[:id])
  end

  def authorize_user
  	if @post.user != current_user
  		return redirect_to root_path
  	end
  	return true

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comm.html.erb
<li>
				<div>
					<p>
					<%= p.content %>
					</p>
					<p class="author-details"><%= p.user.email%> at <%= p.created_at %>
					</p>
					</p>
					<p  class="author-details"><%=  render 'like' , p: p %>
					</p>
				</div>
				
				<p class="comment-destroy-link">
					<%= link_to "X", comment_path(p.id) , method: :delete %>
				</p>
</li>			

app/views/comments/_like.html.erb
                <%if p.likes.find_by_user_id(current_user.id)==nil%>
                <p>
                <p id="like-<%= p.class %>_<%= p.id %>"> Like </p>
                <%= link_to "hereismy" , new_like_path(:id => p.id , :li => p.class , :p => p)  %>
                </p>
                <%else %>
                 <p>
                <p id="like-<%= p.class %>_<%= p.id %>"> Unlike </p>
                <%= link_to "here" , new_like_path(:id => p.id , :li => p.class , :p => p)   %>
                </p>
                <%end%>



                
<p id="like-<%= p.class %>-<%= p.id %>"><%= p.likes.length %></p>

app/views/comments/create.html.erb
create.html.erb

app/views/comments/create.js.erb
$('#comments-<%= @post.id %>').append("<%=  escape_javascript  render 'comm', p: @com  %>");

app/views/friendships/_friend.html.erb
<div id="friend-<%= p.id %>">        
<p><%= p.email%> </p>
<p><%= link_to 'Add Frind' ,new_friendship_path(:id => p.id),remote: true %> </p>
</div>

app/views/friendships/index.html.erb
<main>
<div class="friends-container">
<%= @user.each do |u| %>

<%if current_user.friends.find_by_email(u.email)==nil%>
<%= render 'friend' , p: u %>


<%end%>



<%end%>

</div>












</main>

app/views/friendships/new.js.erb
console.log("i m inside frined")
$('#friend-<%= @myid %>').remove()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Allsocial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'components/test', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'components/test', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header id="body-header">
		<div id="page-logo">
			<%= link_to "/" do%>
				<%= image_tag("reddit-logo.png") %>
			<% end %>
		</div>

		<div id="auth-links">
			<ul>
				<% if !user_signed_in? %>
					<% if !current_page?(new_user_session_path) %>
					<li>
						<p>
							<%= link_to "Sign In", new_user_session_path %>
						</p>
					</li>
					<% end %>
					<% if !current_page?(new_user_registration_path) %>
					<li>
						<p>
							<%= link_to "Sign Up", new_user_registration_path %>
						</p>
					</li>
					<% end %>
				<% else %>
				<li>
					<p><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>
				</li>
				<% end %>
				
			</ul>
		</div>
	</header>

<%= yield %>

</body>
</html>

app/views/likes/destroy.js.erb
$('#like-<%= @class %>-<%= @id %>').html('<%= @here2.likes.length %>')

app/views/likes/new.js.erb
$('#like-<%= @class %>_<%= @id %>').html('<%= @liked %>')
$('#like-<%= @class %>-<%= @id %>').html('<%= @here.likes.length %>')

app/views/likes/toggle_like.js.erb
$('#like-<%= @class %>_<%= @id %>').html('<%= @liked %>')
$('#like-<%= @class %>-<%= @id %>').html('<%= @here.likes.length %>')

app/views/posts/_comm.html.erb
<li>
				<div>
					<p>
					<%= p.content %>
					</p>
					<p class="author-details"><%= p.user.email%> at <%= p.created_at %>
					</p>
					</p>
					<p  class="author-details"><%=  render 'like' , p: p %>
					</p>
				</div>
				
				<p class="comment-destroy-link">
					<%= link_to "X", comment_path(p.id) , method: :delete %>
				</p>
</li>			

app/views/posts/_like.html.erb
                <%if user_signed_in? %>
                <%if p.likes.find_by_user_id(current_user.id)==nil%>
                <p>
                <p id="like-<%= p.class %>_<%= p.id %>"> Like </p>
                <%= link_to "hereismy" , new_like_path(:id => p.id , :li => p.class , :p => p) , remote: true %>
                </p>
                <%else %>
                 <p>
                <p id="like-<%= p.class %>_<%= p.id %>"> Unlike </p>
                <%= link_to "here" , new_like_path(:id => p.id , :li => p.class , :p => p) , remote: true  %>
                </p>
                <%end%>
                <%end%>


                
<p id="like-<%= p.class %>-<%= p.id %>"><%= p.likes.length %></p>

app/views/posts/_post.html.erb
<li id="post-<%= p.id %>" class="post">
	<div class="post-content">
		<div class="text">
			<p >
				<%= p.content %>
			</p>
			<p class="author-details">
				<%= p.user.email%> at <%= p.created_at %>
			</p>
			<p id="like-container" class="author-details">
              
				<p><%= render 'like' , p: p %></p>
			</p>
		</div>
		
		<p class="post-destroy-link">
			<%= link_to "X", post_path(p.id), remote: true, method: :delete %>
		</p>
	</div>
	<div class="post-comments-container">       
		<%= form_for @comment , remote: true do |f| %>
			<%= f.hidden_field :post_id, value: p.id %>
			<%= f.text_area :content, placeholder: "Add Comment" %>
			<%= f.submit %>
		<% end %>
		<ul id="comments-<%= p.id %>" class="comments-list">
			<% p.comments.each do |com| %>
			  <%= render 'comm' ,  p: com  %>
			<% end %>
		</ul>
	</div>
</li>

app/views/posts/create.html.erb
something

app/views/posts/create.js.erb
console.log("I m")
$('#posts-list').prepend("<%= escape_javascript  render 'post', p: @post %>");

app/views/posts/destroy.js.erb
$('#post-<%= @post_id %>').remove();

app/views/posts/index.html.erb
<main>
<%= link_to "Friends",'/friendships/index'%>
	<% if user_signed_in? %>
	<div id="new-post-form-container">
		<%= form_for @post, remote: true do |f| %>
			<%= f.label :content, "Add Post" %>
			<%= f.text_area :content, placeholder: "Type Here" %>
			<%= f.submit %>
		<% end %>
	</div>
	<% end %>

	<div id="posts-list-container">
		<ul id="posts-list">
			<% @posts.each do |post| %>
				<%= render 'post', p: post %>
			<% end %>
		</ul>
	</div>
<%if user_signed_in?%>
<%= @friends.each do |f|%>
<p><%= f.email %></p>
<%end%>
<%end%>

</main>

app/views/posts/like.html.erb
<main>
<%= link_to "Like" , new_like_path(:li => p.class, :id => p.id) %>
<%= p.likes.length %>
</main>